# Generated by Django 5.1.1 on 2024-10-05 09:47

from django.db import migrations, models

def create_language(apps, schema_editor):
    Language = apps.get_model('teams', 'Language')
    Language.objects.create(name='English')
    Language.objects.create(name='Korean')

class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.RunPython(create_language),
    ]
