# Generated by Django 5.1.1 on 2024-10-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo_url',
            field=models.URLField(default='/logos/atl.svg'),
            preserve_default=False,
        ),
    ]
