# Generated by Django 5.1.1 on 2024-10-06 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_logo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='logo_url',
        ),
    ]
