# Generated by Django 5.1.1 on 2024-10-29 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_remove_team_logo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostStatusDisplayName',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=128)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.language')),
                ('post_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.poststatus')),
            ],
            options={
                'unique_together': {('post_status', 'language')},
            },
        ),
    ]
