# Generated by Django 5.1.1 on 2024-11-05 04:51

import django.db.models.deletion
import teams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_poststatusdisplayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcommentreply',
            name='status',
            field=models.ForeignKey(default=teams.models.PostCommentReplyStatus.get_created_role, on_delete=django.db.models.deletion.PROTECT, to='teams.postcommentreplystatus'),
        ),
    ]
