# Generated by Django 5.1.1 on 2024-11-21 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_alter_postcommentreply_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCommentStatusDisplayName',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=128)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.language')),
                ('post_comment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.postcommentstatus')),
            ],
            options={
                'unique_together': {('post_comment_status', 'language')},
            },
        ),
    ]
