# Generated by Django 5.1.1 on 2024-11-28 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_postcommentstatusdisplayname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlike',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='teamlike',
            constraint=models.UniqueConstraint(condition=models.Q(('favorite', True)), fields=('user',), name='unique_team_like'),
        ),
    ]
