# Generated by Django 5.1.1 on 2024-12-11 11:39

from django.db import migrations
from django.db.utils import IntegrityError

def create_teams(apps, schema_editor):
    Team = apps.get_model('teams', 'Team')

    MEM, created = Team.objects.update_or_create(
        id=1610612763,
        defaults={'symbol': 'MEM'}
    )
    HOU, created = Team.objects.update_or_create(
        id=1610612745,
        defaults={'symbol': 'HOU'}
    )
    NYK, created = Team.objects.update_or_create(
        id=1610612752,
        defaults={'symbol': 'NYK'}
    )
    DET, created = Team.objects.update_or_create(
        id=1610612765,
        defaults={'symbol': 'DET'}
    )
    CHA, created = Team.objects.update_or_create(
        id=1610612766,
        defaults={'symbol': 'CHA'}
    )
    MIN, created = Team.objects.update_or_create(
        id=1610612750,
        defaults={'symbol': 'MIN'}
    )
    PHO, created = Team.objects.update_or_create(
        id=1610612756,
        defaults={'symbol': 'PHO'}
    )
    WAS, created = Team.objects.update_or_create(
        id=1610612764,
        defaults={'symbol': 'WAS'}
    )
    UTA, created = Team.objects.update_or_create(
        id=1610612762,
        defaults={'symbol': 'UTA'}
    )
    POR, created = Team.objects.update_or_create(
        id=1610612757,
        defaults={'symbol': 'POR'}
    )
    ORL, created = Team.objects.update_or_create(
        id=1610612753,
        defaults={'symbol': 'ORL'}
    )
    TOR, created = Team.objects.update_or_create(
        id=1610612761,
        defaults={'symbol': 'TOR'}
    )
    CHI, created = Team.objects.update_or_create(
        id=1610612741,
        defaults={'symbol': 'CHI'}
    )
    BKN, created = Team.objects.update_or_create(
        id=1610612751,
        defaults={'symbol': 'BKN'}
    )
    GSW, created = Team.objects.update_or_create(
        id=1610612744,
        defaults={'symbol': 'GSW'}
    )
    NOP, created = Team.objects.update_or_create(
        id=1610612740,
        defaults={'symbol': 'NOP'}
    )
    PHI, created = Team.objects.update_or_create(
        id=1610612755,
        defaults={'symbol': 'PHI'}
    )
    SAC, created = Team.objects.update_or_create(
        id=1610612758,
        defaults={'symbol': 'SAC'}
    )
    IND, created = Team.objects.update_or_create(
        id=1610612754,
        defaults={'symbol': 'IND'}
    )
    ATL, created = Team.objects.update_or_create(
        id=1610612737,
        defaults={'symbol': 'ATL'}
    )
    LAC, created = Team.objects.update_or_create(
        id=1610612746,
        defaults={'symbol': 'LAC'}
    )
    DEN, created = Team.objects.update_or_create(
        id=1610612743,
        defaults={'symbol': 'DEN'}
    )
    OKC, created = Team.objects.update_or_create(
        id=1610612760,
        defaults={'symbol': 'OKC'}
    )
    BOS, created = Team.objects.update_or_create(
        id=1610612738,
        defaults={'symbol': 'BOS'}
    )
    MIL, created = Team.objects.update_or_create(
        id=1610612749,
        defaults={'symbol': 'MIL'}
    )
    MIA, created = Team.objects.update_or_create(
        id=1610612748,
        defaults={'symbol': 'MIA'}
    )
    CAV, created = Team.objects.update_or_create(
        id=1610612739,
        defaults={'symbol': 'CAV'}
    )
    LAL, created = Team.objects.update_or_create(
        id=1610612747,
        defaults={'symbol': 'LAL'}
    )
    DAL, created = Team.objects.update_or_create(
        id=1610612742,
        defaults={'symbol': 'DAL'}
    )
    SAS, created = Team.objects.update_or_create(
        id=1610612759,
        defaults={'symbol': 'SAS'}
    )

    Language = apps.get_model('teams', 'Language')
    Korean = Language.objects.get(name='Korean')
    English = Language.objects.get(name='English')

    TeamName = apps.get_model('teams', 'TeamName')
    try:
        TeamName.objects.update_or_create(
            team=MEM,
            language=Korean,
            defaults={'name': '멤피스 그리즐리스'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=MEM,
            language=English,
            defaults={'name': 'Memphis Grizzlies'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=HOU,
            language=Korean,
            defaults={'name': '휴스턴 로켓츠'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=HOU,
            language=English,
            defaults={'name': 'Houston Rockets'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=NYK,
            language=Korean,
            defaults={'name': '뉴욕 닉스'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=NYK,
            language=English,
            defaults={'name': 'New York Knicks'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=DET,
            language=Korean,
            defaults={'name': '디트로이트 피스톤즈'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=DET,
            language=English,
            defaults={'name': 'Detroit Pistons'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=CHA,
            language=Korean,
            defaults={'name': '샬럿 호넷즈'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=CHA,
            language=English,
            defaults={'name': 'Charlotte Hornets'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=MIN,
            language=Korean,
            defaults={'name': '미네소타 팀버울브스'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=MIN,
            language=English,
            defaults={'name': 'Minnesota Timberwolves'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=PHO,
            language=Korean,
            defaults={'name': '피닉스 선즈'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=PHO,
            language=English,
            defaults={'name': 'Phoenix Suns'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=WAS,
            language=Korean,
            defaults={'name': '워싱턴 위저즈'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=WAS,
            language=English,
            defaults={'name': 'Washington Wizards'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=UTA,
            language=Korean,
            defaults={'name': '유타 재즈'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=UTA,
            language=English,
            defaults={'name': 'Utah Jazz'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=POR,
            language=Korean,
            defaults={'name': '포틀랜드 트레일 블레이저스'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=POR,
            language=English,
            defaults={'name': 'Portland Trail Blazers'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=ORL,
            language=Korean,
            defaults={'name': '올랜도 매직'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=ORL,
            language=English,
            defaults={'name': 'Orlando Magic'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=TOR,
            language=Korean,
            defaults={'name': '토론토 랩터스'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=TOR,
            language=English,
            defaults={'name': 'Toronto Raptors'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=CHI,
            language=Korean,
            defaults={'name': '시카고 불스'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=CHI,
            language=English,
            defaults={'name': 'Chicago Bulls'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=BKN,
            language=Korean,
            defaults={'name': '브루클린 네츠'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=BKN,
            language=English,
            defaults={'name': 'Brooklyn Nets'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=GSW,
            language=Korean,
            defaults={'name': '골든스테이트 워리어스'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=GSW,
            language=English,
            defaults={'name': 'Golden State Warriors'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=NOP,
            language=Korean,
            defaults={'name': '뉴올리언스 펠리컨스'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=NOP,
            language=English,
            defaults={'name': 'New Orleans Pelicans'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=PHI,
            language=Korean,
            defaults={'name': '필라델피아 세븐티식서스'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=PHI,
            language=English,
            defaults={'name': 'Philadelphia 76ers'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=SAC,
            language=Korean,
            defaults={'name': '새크라멘토 킹스'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=SAC,
            language=English,
            defaults={'name': 'Sacramento Kings'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=IND,
            language=Korean,
            defaults={'name': '인디애나 페이서스'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=IND,
            language=English,
            defaults={'name': 'Indiana Pacers'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=ATL,
            language=Korean,
            defaults={'name': '애틀랜타 호크스'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=ATL,
            language=English,
            defaults={'name': 'Atlanta Hawks'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=LAC,
            language=Korean,
            defaults={'name': '로스앤젤레스 클리퍼스'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=LAC,
            language=English,
            defaults={'name': 'Los Angeles Clippers'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=DEN,
            language=Korean,
            defaults={'name': '덴버 너기츠'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=DEN,
            language=English,
            defaults={'name': 'Denver Nuggets'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=OKC,
            language=Korean,
            defaults={'name': '오클라호마시티 썬더'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=OKC,
            language=English,
            defaults={'name': 'Oklahoma City Thunder'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=BOS,
            language=Korean,
            defaults={'name': '보스턴 셀틱스'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=BOS,
            language=English,
            defaults={'name': 'Boston Celtics'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=MIL,
            language=Korean,
            defaults={'name': '밀워키 버크스'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=MIL,
            language=English,
            defaults={'name': 'Milwaukee Bucks'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=MIA,
            language=Korean,
            defaults={'name': '마이애미 히트'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=MIA,
            language=English,
            defaults={'name': 'Miami Heat'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=CAV,
            language=Korean,
            defaults={'name': '클리블랜드 캐벌리어스'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=CAV,
            language=English,
            defaults={'name': 'Cleveland Cavaliers'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=LAL,
            language=Korean,
            defaults={'name': '로스앤젤레스 레이커스'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=LAL,
            language=English,
            defaults={'name': 'Los Angeles Lakers'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=DAL,
            language=Korean,
            defaults={'name': '댈러스 매버릭스'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=DAL,
            language=English,
            defaults={'name': 'Dallas Mavericks'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=SAS,
            language=Korean,
            defaults={'name': '샌안토니오 스퍼스'}
        )
    except IntegrityError:
        pass

    try:
        TeamName.objects.update_or_create(
            team=SAS,
            language=English,
            defaults={'name': 'San Antonio Spurs'}
        )
    except IntegrityError:
        pass

class Migration(migrations.Migration):
    dependencies = [
        ('teams', '0008_teamlike_favorite_teamlike_unique_team_like'),
    ]

    operations = [
        migrations.RunPython(create_teams),
    ]
