# Generated by Django 5.1.1 on 2024-12-24 09:02

from django.db import migrations


def create_post_statuses(apps, schema_editor):
    PostStatus = apps.get_model('teams', 'PostStatus')
    PostStatus.objects.get_or_create(name='created')
    PostStatus.objects.get_or_create(name='hidden')
    PostStatus.objects.get_or_create(name='deleted')

    Language = apps.get_model('teams', 'Language')
    Korean = Language.objects.get(name='Korean')
    English = Language.objects.get(name='English')

    PostStatusDisplayName = apps.get_model('teams', 'PostStatusDisplayName')
    PostStatusDisplayName.objects.update_or_create(
        post_status=PostStatus.objects.get(name='created'), language=Korean, defaults={'display_name': '게시하기'})
    PostStatusDisplayName.objects.update_or_create(
        post_status=PostStatus.objects.get(name='hidden'), language=Korean, defaults={'display_name': '비공개'})
    PostStatusDisplayName.objects.update_or_create(
        post_status=PostStatus.objects.get(name='deleted'), language=Korean, defaults={'display_name': '삭제'})
    PostStatusDisplayName.objects.update_or_create(
        post_status=PostStatus.objects.get(name='created'), language=English, defaults={'display_name': 'Publish'})
    PostStatusDisplayName.objects.update_or_create(
        post_status=PostStatus.objects.get(name='hidden'), language=English, defaults={'display_name': 'Hide'})
    PostStatusDisplayName.objects.update_or_create(
        post_status=PostStatus.objects.get(name='deleted'), language=English, defaults={'display_name': 'Delete'})

class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_auto_20241211_1139'),
    ]

    operations = [
        migrations.RunPython(create_post_statuses),
    ]
