# Generated by Django 5.1.1 on 2024-12-24 10:11

from django.db import migrations

def create_post_comment_status(apps, schema_editor):
    PostCommentStatus = apps.get_model('teams', 'PostCommentStatus')
    created, _ = PostCommentStatus.objects.get_or_create(name='created')
    deleted, _ = PostCommentStatus.objects.get_or_create(name='deleted')

    PostCommentStatusDisplayName = apps.get_model('teams', 'PostCommentStatusDisplayName')
    Language = apps.get_model('teams', 'Language')

    english = Language.objects.get(name='English')
    PostCommentStatusDisplayName.objects.update_or_create(post_comment_status=created, language=english, defaults={'display_name': 'Create'})
    PostCommentStatusDisplayName.objects.update_or_create(post_comment_status=deleted, language=english, defaults={'display_name': 'Delete'})

    korean = Language.objects.get(name='Korean')
    PostCommentStatusDisplayName.objects.update_or_create(post_comment_status=created, language=korean, defaults={'display_name': '생성하기'})
    PostCommentStatusDisplayName.objects.update_or_create(post_comment_status=deleted, language=korean, defaults={'display_name': '삭제하기'})


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_auto_20241224_0902'),
    ]

    operations = [
        migrations.RunPython(create_post_comment_status),
    ]
