# Generated by Django 5.1.1 on 2024-12-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_auto_20241224_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=512),
        ),
    ]
