# Generated by Django 5.1.1 on 2024-10-14 05:17

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_create_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=users.models.Role.get_regular_user_role, on_delete=django.db.models.deletion.PROTECT, to='users.role'),
        ),
    ]
