# Generated by Django 5.1.1 on 2024-10-17 12:34

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_role_name_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=users.utils.generate_random_username, max_length=128, unique=True),
        ),
    ]
