# Generated by Django 5.1.1 on 2024-11-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userchat_userchatparticipant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchatparticipantmessage',
            name='read_by_receiver',
            field=models.BooleanField(default=False),
        ),
    ]
