# Generated by Django 5.1.1 on 2024-11-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userchatparticipantmessage_read_by_receiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChatStatus',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='userchatparticipant',
            name='chat_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userchatparticipant',
            name='last_read_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
