# Generated by Django 5.1.1 on 2024-11-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userchatstatus_userchatparticipant_chat_blocked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchatparticipantmessage',
            name='read_by_receiver',
        ),
    ]
