# Generated by Django 5.1.1 on 2024-11-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20241107_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchatparticipant',
            name='last_deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
