# Generated by Django 5.1.1 on 2024-11-07 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userchatparticipant_last_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchat',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.userchatstatus'),
        ),
    ]
