# Generated by Django 5.1.1 on 2024-11-07 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userchat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchat',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.userchatstatus'),
        ),
    ]
