# Generated by Django 5.1.1 on 2024-11-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_userchat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchatparticipant',
            name='last_read_at',
            field=models.DateTimeField(auto_now=True, help_text='Last time the other user read the chat'),
        ),
    ]
