# Generated by Django 5.1.1 on 2024-11-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_userchat_status_delete_userchatstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
