# Generated by Django 5.1.1 on 2024-11-21 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_chat_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlike',
            name='liked_user',
            field=models.ForeignKey(help_text='User that the user liked', on_delete=django.db.models.deletion.CASCADE, related_name='liked_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
