# Generated by Django 5.1.1 on 2025-01-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_notification_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
