# Generated by Django 5.1.1 on 2025-01-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_user_login_notification_enabled'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userchatparticipantmessage',
            index=models.Index(fields=['sender', '-created_at'], name='users_userc_sender__7c39ab_idx'),
        ),
    ]
