# Generated by Django 5.1.1 on 2025-01-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_userchatparticipantmessage_users_userc_sender__7c39ab_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchatparticipant',
            name='last_read_at',
            field=models.DateTimeField(auto_now=True, help_text='Last time the user read the chat'),
        ),
    ]
