# Generated by Django 5.1.1 on 2024-11-08 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('teams', '0006_alter_postcommentreply_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTypeDisplayName',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=256)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.language')),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.reporttype')),
            ],
        ),
    ]
