# Generated by Django 5.1.1 on 2024-11-08 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_remove_inquirymessage_user_inquirymoderator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='type',
            new_name='inquiry_type',
        ),
    ]
