# Generated by Django 5.1.1 on 2024-11-08 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_rename_type_inquiry_inquiry_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='description',
        ),
    ]
