# Generated by Django 5.1.1 on 2024-11-08 16:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_remove_inquiry_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='last_read_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Last time the user read the inquiry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquirymoderator',
            name='last_read_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Last time the moderator read the inquiry'),
            preserve_default=False,
        ),
    ]
