# Generated by Django 5.1.1 on 2024-11-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_inquiry_last_read_at_inquirymoderator_last_read_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='solved',
            new_name='resolved',
        ),
    ]
