# Generated by Django 5.1.1 on 2025-01-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_rename_solved_report_resolved'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inquirymessage',
            index=models.Index(fields=['inquiry', '-created_at'], name='management__inquiry_9bb34c_idx'),
        ),
        migrations.AddIndex(
            model_name='inquirymoderatormessage',
            index=models.Index(fields=['inquiry_moderator', '-created_at'], name='management__inquiry_1f8ed0_idx'),
        ),
    ]
