# Generated by Django 5.1.1 on 2025-01-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='picture_url_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='redirect_url_template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
