# Generated by Django 5.1.1 on 2025-01-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notificationtemplate_picture_url_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='picture_url_template',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='redirect_url_template',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
