# Generated by Django 5.1.1 on 2025-01-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_auto_20250102_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrecipient',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
