# Generated by Django 5.1.1 on 2025-01-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_notificationrecipient_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplatetype',
            name='color_code',
            field=models.CharField(default='#423F3E', max_length=7),
        ),
    ]
