# Generated by Django 5.1.1 on 2025-01-09 09:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_notificationtemplatetype_color_code'),
        ('teams', '0014_auto_20250107_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplateTypeDisplayName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams.language')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.notificationtemplatetype')),
            ],
            options={
                'unique_together': {('type', 'language')},
            },
        ),
    ]
