# Generated by Django 5.1.1 on 2024-10-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_linescore_line_score_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(help_text="Unique identifier for the game (e.g., '0022400061').", max_length=50, primary_key=True, serialize=False),
        ),
    ]
