# Generated by Django 5.1.1 on 2024-10-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_tv_broadcaster_abbreviation',
            field=models.CharField(blank=True, help_text='Away TV broadcaster abbreviation.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_tv_broadcaster_abbreviation',
            field=models.CharField(blank=True, help_text='Home TV broadcaster abbreviation.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='live_pc_time',
            field=models.CharField(blank=True, help_text='Live PC time (if applicable).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='natl_tv_broadcaster_abbreviation',
            field=models.CharField(blank=True, help_text="National TV broadcaster abbreviation (e.g., 'TNT').", max_length=50, null=True),
        ),
    ]
