# Generated by Django 5.1.1 on 2024-10-10 07:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_remove_linescore_pts'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date and time the game was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time the game was last updated.'),
        ),
        migrations.AddField(
            model_name='linescore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date and time the line score was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linescore',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time the line score was last updated.'),
        ),
    ]
