# Generated by Django 5.1.1 on 2024-10-23 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_teamstatistics'),
        ('teams', '0004_remove_team_logo_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamstatistics',
            options={'ordering': ['game__game_date_est'], 'verbose_name': 'Team Statistics', 'verbose_name_plural': 'Team Statistics'},
        ),
        migrations.AlterUniqueTogether(
            name='teamstatistics',
            unique_together={('team', 'game')},
        ),
    ]
