# Generated by Django 5.1.1 on 2025-02-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_teamstatistics_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamechat',
            name='mute_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamechatmute',
            name='mute_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
