# Generated by Django 5.1.1 on 2025-02-12 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_gamechat_mute_until_gamechatmute_mute_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamechatban',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='games.gamechat'),
        ),
        migrations.AddField(
            model_name='gamechatban',
            name='reason',
            field=models.TextField(default='No reason provided'),
        ),
        migrations.AddField(
            model_name='gamechatmute',
            name='reason',
            field=models.TextField(default='No reason provided'),
        ),
        migrations.AlterUniqueTogether(
            name='gamechatban',
            unique_together={('chat', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='gamechatmute',
            unique_together={('chat', 'user')},
        ),
    ]
