# Generated by Django 5.1.1 on 2025-02-13 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_gamechatban_chat_gamechatban_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamechatban',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.gamechatmessage'),
        ),
        migrations.AddField(
            model_name='gamechatmute',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.gamechatmessage'),
        ),
    ]
