# Generated by Django 5.1.1 on 2025-02-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_gamechatban_message_gamechatmute_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamechatmute',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
