# Generated by Django 5.1.1 on 2025-02-14 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_gamechatban_disabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gamechatban',
            constraint=models.UniqueConstraint(condition=models.Q(('disabled', True)), fields=('user',), name='unique_chat_ban'),
        ),
        migrations.AddConstraint(
            model_name='gamechatmute',
            constraint=models.UniqueConstraint(condition=models.Q(('disabled', True)), fields=('user',), name='unique_chat_mute'),
        ),
    ]
