# Generated by Django 5.1.1 on 2025-02-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_alter_gamechatban_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamechat',
            name='mute_mode',
            field=models.BooleanField(default=False),
        ),
    ]
