# Generated by Django 5.1.1 on 2025-02-23 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_gamechat_mute_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gamechatban',
            name='unique_chat_ban',
        ),
        migrations.RemoveConstraint(
            model_name='gamechatmute',
            name='unique_chat_mute',
        ),
        migrations.AddConstraint(
            model_name='gamechatban',
            constraint=models.UniqueConstraint(condition=models.Q(('disabled', False)), fields=('chat', 'user'), name='unique_chat_ban'),
        ),
        migrations.AddConstraint(
            model_name='gamechatmute',
            constraint=models.UniqueConstraint(condition=models.Q(('disabled', False)), fields=('chat', 'user'), name='unique_chat_mute'),
        ),
    ]
