# Generated by Django 5.1.1 on 2025-02-28 14:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_remove_gamechatban_unique_chat_ban_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameChatModifiedMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gamechatmessage')),
            ],
        ),
    ]
