# Generated by Django 5.1.1 on 2024-10-22 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0004_remove_team_logo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('player_last_name', models.CharField(max_length=100)),
                ('player_first_name', models.CharField(max_length=100)),
                ('player_slug', models.SlugField(max_length=150, unique=True)),
                ('position', models.CharField(blank=True, max_length=20, null=True)),
                ('height', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('college', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('draft_year', models.IntegerField(blank=True, null=True)),
                ('draft_round', models.IntegerField(blank=True, null=True)),
                ('draft_number', models.IntegerField(blank=True, null=True)),
                ('roster_status', models.FloatField(blank=True, null=True)),
                ('stats_timeframe', models.CharField(blank=True, max_length=20, null=True)),
                ('from_year', models.IntegerField(blank=True, null=True)),
                ('to_year', models.IntegerField(blank=True, null=True)),
                ('pts', models.FloatField(blank=True, null=True)),
                ('reb', models.FloatField(blank=True, null=True)),
                ('ast', models.FloatField(blank=True, null=True)),
                ('is_defunct', models.BooleanField(default=False)),
                ('team_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teams.team')),
            ],
        ),
    ]
