# Generated by Django 5.1.1 on 2024-10-22 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('teams', '0004_remove_team_logo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='person_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_slug',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_defunct',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team_id',
        ),
        migrations.AddField(
            model_name='player',
            name='jersey_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.CharField(default='USA', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='from_year',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.CharField(default='6-4', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(default='G', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='roster_status',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='stats_timeframe',
            field=models.CharField(default='Season', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='to_year',
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.FloatField(default=198.0),
            preserve_default=False,
        ),
    ]
