# Generated by Django 5.1.1 on 2024-10-22 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_rename_player_first_name_player_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=10)),
                ('order', models.IntegerField()),
                ('position', models.CharField(max_length=5)),
                ('starter', models.BooleanField(default=False)),
                ('assists', models.IntegerField()),
                ('blocks', models.IntegerField()),
                ('blocks_received', models.IntegerField()),
                ('field_goals_attempted', models.IntegerField()),
                ('field_goals_made', models.IntegerField()),
                ('field_goals_percentage', models.FloatField()),
                ('fouls_offensive', models.IntegerField()),
                ('fouls_drawn', models.IntegerField()),
                ('fouls_personal', models.IntegerField()),
                ('fouls_technical', models.IntegerField()),
                ('free_throws_attempted', models.IntegerField()),
                ('free_throws_made', models.IntegerField()),
                ('free_throws_percentage', models.FloatField()),
                ('minus', models.FloatField()),
                ('minutes', models.CharField(max_length=20)),
                ('plus', models.FloatField()),
                ('plus_minus_points', models.FloatField()),
                ('points', models.IntegerField()),
                ('points_fast_break', models.IntegerField()),
                ('points_in_the_paint', models.IntegerField()),
                ('points_second_chance', models.IntegerField()),
                ('rebounds_defensive', models.IntegerField()),
                ('rebounds_offensive', models.IntegerField()),
                ('rebounds_total', models.IntegerField()),
                ('steals', models.IntegerField()),
                ('three_pointers_attempted', models.IntegerField()),
                ('three_pointers_made', models.IntegerField()),
                ('three_pointers_percentage', models.FloatField()),
                ('turnovers', models.IntegerField()),
                ('two_pointers_attempted', models.IntegerField()),
                ('two_pointers_made', models.IntegerField()),
                ('two_pointers_percentage', models.FloatField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
        ),
    ]
