# Generated by Django 5.1.1 on 2024-10-22 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_teamstatistics'),
        ('players', '0003_playerstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatistics',
            name='game',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.game'),
        ),
    ]
