# Generated by Django 5.1.1 on 2024-10-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_playerstatistics_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
