# Generated by Django 5.1.1 on 2024-10-23 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_alter_player_weight'),
        ('teams', '0004_remove_team_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatistics',
            name='team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
