# Generated by Django 5.1.1 on 2024-10-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_playerstatistics_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatistics',
            name='position',
            field=models.CharField(default='', max_length=5),
        ),
    ]
