# Generated by Django 5.1.1 on 2024-10-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_alter_playerstatistics_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatistics',
            name='position',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
