# Generated by Django 5.1.1 on 2024-10-23 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_teamstatistics_options_and_more'),
        ('players', '0008_alter_playerstatistics_position'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerstatistics',
            unique_together={('player', 'game')},
        ),
    ]
