# Generated by Django 5.1.1 on 2024-10-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_alter_playerstatistics_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='from_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='roster_status',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='to_year',
            field=models.IntegerField(null=True),
        ),
    ]
