# Generated by Django 5.1.1 on 2024-10-26 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_alter_player_from_year_alter_player_roster_status_and_more'),
        ('teams', '0004_remove_team_logo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCareerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_id', models.CharField(max_length=20)),
                ('player_age', models.FloatField()),
                ('games_played', models.IntegerField()),
                ('games_started', models.IntegerField()),
                ('minutes', models.FloatField()),
                ('field_goals_made', models.FloatField()),
                ('field_goals_attempted', models.FloatField()),
                ('field_goals_percentage', models.FloatField()),
                ('three_point_field_goals_made', models.FloatField()),
                ('three_point_field_goals_attempted', models.FloatField()),
                ('three_point_field_goals_percentage', models.FloatField()),
                ('free_throws_made', models.FloatField()),
                ('free_throws_attempted', models.FloatField()),
                ('free_throws_percentage', models.FloatField()),
                ('rebounds_offensive', models.FloatField()),
                ('rebounds_defensive', models.FloatField()),
                ('rebounds_total', models.FloatField()),
                ('assists', models.FloatField()),
                ('steals', models.FloatField()),
                ('blocks', models.FloatField()),
                ('turnovers', models.FloatField()),
                ('personal_fouls', models.FloatField()),
                ('points', models.FloatField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('team', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'unique_together': {('player', 'season_id', 'team')},
            },
        ),
    ]
