# Generated by Django 5.1.1 on 2024-11-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_playercareerstatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
